import type { Resource } from "@/lib/types";

/**
 * The Library — REAL public-domain content. Not sample data.
 *
 * Every record is a genuine, findable, legally-clean public-domain edition. Per §6.3 the
 * Library never hosts files; each record links to a legitimate host (Internet Archive) and
 * states its rights explicitly. Source URLs are stable Internet Archive identifiers.
 */
export const LIBRARY: Resource[] = [
  {
    type: "resource",
    id: "yoga-sutras-woods",
    slug: "yoga-sutras-of-patanjali-woods-1914",
    sample: false,
    featured: true,
    title: "The Yoga System of Patañjali",
    author: "Translated by James Haughton Woods",
    subject: "Yoga philosophy",
    tradition: "Classical / Pātañjala Yoga",
    description:
      "A scholarly 1914 translation of the Yoga Sūtras with the Vyāsa commentary and Vācaspati Miśra's gloss — one of the earliest rigorous English renderings of the foundational text of classical Yoga.",
    level: "experienced-teacher",
    rights: "Public domain (published 1914; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/yogasystemofpata00wooduoft" },
  },
  {
    type: "resource",
    id: "yoga-sutras-vivekananda",
    slug: "raja-yoga-vivekananda-1896",
    sample: false,
    title: "Rāja Yoga",
    author: "Swami Vivekananda",
    subject: "Yoga philosophy",
    tradition: "Vedānta / Rāja Yoga",
    description:
      "Vivekananda's 1896 lectures on Rāja Yoga, including his translation and commentary on Patañjali's Yoga Sūtras — historically the text that introduced Yoga philosophy to a wide Western readership.",
    level: "open",
    rights: "Public domain (published 1896; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/rjayoga00viveuoft" },
  },
  {
    type: "resource",
    id: "hatha-yoga-pradipika",
    slug: "hatha-yoga-pradipika-sinh-1914",
    sample: false,
    featured: true,
    title: "The Haṭha Yoga Pradīpikā",
    author: "Translated by Pancham Sinh",
    subject: "Asana and methodology",
    tradition: "Haṭha Yoga",
    description:
      "Svātmārāma's classic 15th-century manual of Haṭha Yoga in Pancham Sinh's 1914 translation — āsana, prāṇāyāma, mudrā and the methodology of practice.",
    level: "teacher",
    rights: "Public domain (published 1914; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/hathayogapradipi00svat" },
    plate: {
      credit: "Title page, Pancham Sinh translation (1914)",
      licence: "Public domain",
    },
  },
  {
    type: "resource",
    id: "gheranda-samhita",
    slug: "gheranda-samhita-vasu-1914",
    sample: false,
    title: "The Gheraṇḍa Saṃhitā",
    author: "Translated by Rai Bahadur Srisa Chandra Vasu",
    subject: "Pranayama",
    tradition: "Haṭha Yoga",
    description:
      "A foundational Haṭha Yoga text framed as a dialogue between the sage Gheraṇḍa and Chaṇḍa Kāpāli, covering the sevenfold path of practice — ṣaṭkarma, āsana, mudrā, pratyāhāra, prāṇāyāma, dhyāna and samādhi.",
    level: "teacher",
    rights: "Public domain (published 1914; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/gherandasamhita00gheruoft" },
  },
  {
    type: "resource",
    id: "siva-samhita",
    slug: "siva-samhita-vasu-1914",
    sample: false,
    title: "The Śiva Saṃhitā",
    author: "Translated by Rai Bahadur Srisa Chandra Vasu",
    subject: "Yoga philosophy",
    tradition: "Haṭha / Tantric Yoga",
    description:
      "A Tantric treatise on Yoga philosophy and practice, addressing the subtle body, nāḍīs, cakras and the discipline of the practitioner, in Vasu's early-20th-century translation.",
    level: "experienced-teacher",
    rights: "Public domain (published 1914; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/sivasamhita00vasuuoft" },
  },
  {
    type: "resource",
    id: "bhagavad-gita-arnold",
    slug: "bhagavad-gita-arnold-1885",
    sample: false,
    title: "The Song Celestial (Bhagavad Gītā)",
    author: "Translated by Sir Edwin Arnold",
    subject: "Texts and commentaries",
    tradition: "Vedānta",
    description:
      "Edwin Arnold's 1885 verse translation of the Bhagavad Gītā — the dialogue between Arjuna and Kṛṣṇa on duty, action and the paths of Yoga, rendered in English blank verse.",
    level: "open",
    rights: "Public domain (published 1885; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/songcelestialorb00arno" },
  },
  {
    type: "resource",
    id: "bhagavad-gita-besant",
    slug: "bhagavad-gita-besant-1895",
    sample: false,
    title: "The Bhagavad Gītā (Besant translation)",
    author: "Translated by Annie Besant",
    subject: "Texts and commentaries",
    tradition: "Vedānta",
    description:
      "Annie Besant's close prose translation of the Bhagavad Gītā (1895), widely used for study alongside verse renderings.",
    level: "open",
    rights: "Public domain (published 1895; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/bhagavadgita00besauoft" },
  },
  {
    type: "resource",
    id: "upanishads-muller-1",
    slug: "upanishads-muller-sbe-vol1",
    sample: false,
    title: "The Upaniṣads, Part I (Sacred Books of the East, Vol. 1)",
    author: "Translated by F. Max Müller",
    subject: "Texts and commentaries",
    tradition: "Vedānta",
    description:
      "Max Müller's translation of principal Upaniṣads in the Sacred Books of the East series (1879) — the philosophical bedrock underlying much of Yoga's view of the self and reality.",
    level: "experienced-teacher",
    rights: "Public domain (published 1879; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/upanishads01ml" },
  },
  {
    type: "resource",
    id: "susruta-samhita",
    slug: "susruta-samhita-bhishagratna",
    sample: false,
    title: "An English Translation of the Suśruta Saṃhitā",
    author: "Translated by Kaviraj Kunja Lal Bhishagratna",
    subject: "Ayurveda",
    tradition: "Āyurveda",
    description:
      "An early-20th-century translation of the Suśruta Saṃhitā, a classical Āyurvedic compendium — useful context for teachers working at the intersection of Yoga and traditional Indian medicine.",
    level: "experienced-teacher",
    rights: "Public domain (early 20th century; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/englishtranslati01susruoft" },
  },
  {
    type: "resource",
    id: "sanskrit-grammar-macdonell",
    slug: "sanskrit-grammar-macdonell",
    sample: false,
    title: "A Sanskrit Grammar for Students",
    author: "Arthur Anthony Macdonell",
    subject: "Sanskrit",
    tradition: "Sanskrit studies",
    description:
      "A widely-used primer of classical Sanskrit grammar — a practical starting point for teachers who want to read source terms and verses in the original.",
    level: "open",
    rights: "Public domain (early 20th century; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/sanskritgrammarf00macduoft" },
  },
  {
    type: "resource",
    id: "sanskrit-dictionary-monier",
    slug: "sanskrit-english-dictionary-monier-williams",
    sample: false,
    title: "A Sanskrit–English Dictionary",
    author: "Sir Monier Monier-Williams",
    subject: "Sanskrit",
    tradition: "Sanskrit studies",
    description:
      "The standard reference dictionary of classical Sanskrit — indispensable for accurate reading of technical Yoga terminology.",
    level: "open",
    rights: "Public domain (published 1899; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/sanskritenglishd00moniuoft" },
  },
  {
    type: "resource",
    id: "dhammapada-sbe",
    slug: "dhammapada-muller-sbe",
    sample: false,
    title: "The Dhammapada (Sacred Books of the East)",
    author: "Translated by F. Max Müller",
    subject: "Meditation",
    tradition: "Buddhist / contemplative",
    description:
      "A classic collection of verses on the disciplined mind — read by many Yoga practitioners for its clear teaching on attention, restraint and equanimity.",
    level: "open",
    rights: "Public domain (published 1881; copyright expired).",
    source: { name: "Internet Archive", url: "https://archive.org/details/dhammapada00mueluoft" },
  },
];
